import Head from "next/head";
import { useQuery } from "urql";
import { PRODUCT_QUERY } from "queries/query";

export default function Home() {
  const [results] = useQuery({ query: PRODUCT_QUERY });
  console.log(results);
  return (
    <>
      <Head>
        <title>Good Soup.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Good Soup.</h1>
        <pre>{JSON.stringify(results, null, 2)}</pre>
      </main>
    </>
  );
}
