import Head from 'next/head';
import { useQuery } from 'urql';
import { PRODUCT_QUERY } from 'queries/query';
import Product from '@/components/product';
import { Gallery } from '@/styles/Gallery';

export default function Home() {
	const [results] = useQuery({ query: PRODUCT_QUERY });
	const { data, fetching, error } = results;

	if (fetching) return <p>Loading...</p>;
	if (error) return <p>Oh no... {error.message}</p>;

	const products = data.products.data;
	const variants = {
		hidden: { opacity: 0 },
		visible: { opacity: 1 },
	};
	const item = {
		hidden: { opacity: 0, scale: 0.8 },
		visible: { opacity: 1, scale: 1 },
	};

	return (
		<>
			<Head>
				<title>Good Soup.</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Gallery
					variants={variants}
					initial="hidden"
					animate="visible"
					transition={{ staggerChildren: 0.05, delayChildren: 0.2 }}
				>
					{products.map((product) => (
						<Product
							variants={item}
							key={product.attributes.slug}
							product={product}
						/>
					))}
				</Gallery>
			</main>
		</>
	);
}
